steps:
  # Step to schedule the training pipeline
  - id: schedule-training-pipeline
    name: python:3.10.14
    entrypoint: /bin/sh
    args:
      - -c
      - |
        # Install Poetry
        echo "################################################################################"
        echo "# Installing Poetry..."
        echo "################################################################################"
        curl -sSL https://install.python-poetry.org | python3 - && \
        export PATH="/builder/home/.local/bin:$$PATH" && \
        echo "Poetry installed. Path updated."

        # Install dependencies
        echo "################################################################################"
        echo "# Installing Python dependencies..."
        echo "################################################################################"
        make install

        # Navigate to the source directory
        echo "################################################################################"
        echo "# Changing directory to pipelines..."
        echo "################################################################################"
        cd pipelines && \

        # Run schedule_pipeline for training
        echo "################################################################################"
        echo "# Scheduling training pipeline..."
        echo "################################################################################"
        poetry run python -m src.pipelines.utils.schedule_pipeline \
          --pipeline_type=training \
          --template_path=https://${_TEST_VERTEX_LOCATION}-kfp.pkg.dev/${_TEST_VERTEX_PROJECT_ID}/mlops-pipeline-repo/taxifare-training-pipeline/${_TRAINING_TAG_NAME} \
          --pipeline_root=${_TEST_VERTEX_PIPELINE_ROOT} \
          --display_name=${_ENV}-training-pipeline \
          --schedule_name=${_ENV}-training-schedule \
          --cron="0 * * * *"
    env:
      - VERTEX_LOCATION=${_TEST_VERTEX_LOCATION}
      - VERTEX_PROJECT_ID=${_TEST_VERTEX_PROJECT_ID}
      - BQ_LOCATION=${_TEST_BQ_LOCATION}
      - VERTEX_PIPELINE_ROOT=${_TEST_VERTEX_PIPELINE_ROOT}
      - VERTEX_SA_EMAIL=${_TEST_VERTEX_SA_EMAIL}

  # Step to schedule the prediction pipeline
  - id: schedule-prediction-pipeline
    name: python:3.10.14
    entrypoint: /bin/sh
    args:
      - -c
      - |
        # Install Poetry
        echo "################################################################################"
        echo "# Installing Poetry..."
        echo "################################################################################"
        curl -sSL https://install.python-poetry.org | python3 - && \
        export PATH="/builder/home/.local/bin:$$PATH" && \
        echo "Poetry installed. Path updated."

        # Install dependencies
        echo "################################################################################"
        echo "# Installing Python dependencies..."
        echo "################################################################################"
        make install

        # Navigate to the source directory
        echo "################################################################################"
        echo "# Changing directory to pipelines..."
        echo "################################################################################"
        cd pipelines && \

        # Run schedule_pipeline for prediction
        echo "################################################################################"
        echo "# Scheduling prediction pipeline..."
        echo "################################################################################"
        poetry run python -m src.pipelines.utils.schedule_pipeline \
          --pipeline_type=prediction \
          --template_path=https://${_TEST_VERTEX_LOCATION}-kfp.pkg.dev/${_TEST_VERTEX_PROJECT_ID}/mlops-pipeline-repo/taxifare-batch-prediction-pipeline/${_PREDICTION_TAG_NAME} \
          --pipeline_root=${_TEST_VERTEX_PIPELINE_ROOT} \
          --display_name=${_ENV}-prediction-pipeline \
          --schedule_name=${_ENV}-prediction-schedule \
          --cron="0 * * * *"
    env:
      - VERTEX_LOCATION=${_TEST_VERTEX_LOCATION}
      - VERTEX_PROJECT_ID=${_TEST_VERTEX_PROJECT_ID}
      - BQ_LOCATION=${_TEST_BQ_LOCATION}
      - VERTEX_PIPELINE_ROOT=${_TEST_VERTEX_PIPELINE_ROOT}
      - VERTEX_SA_EMAIL=${_TEST_VERTEX_SA_EMAIL}

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 18000s  # 5 hours
